var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dom",
            "mon": "Lun",
            "tue": "Mar",
            "wed": "Mie",
            "thu": "Jue",
            "fri": "Vie",
            "sat": "Sab",
            "jan": "Ene  ",
            "feb": "Feb  ",
            "mar": "Mar  ",
            "apr": "Abr  ",
            "may": "May  ",
            "jun": "Jun  ",
            "jul": "Jul  ",
            "aug": "Ago  ",
            "sep": "Sep  ",
            "oct": "Oct  ",
            "nov": "Nov  ",
            "dec": "Dic  "
        },
        "no_implemented": "Aun no implementado.",
        "to_date_view": "Da click para ver la fecha actual.",
        "i_undefined": "No definido.",
        "allday_event": "Todo el dia.",
        "repeat_event": "Evento de repetción.",
        "time": "Fecha",
        "event": "Evento",
        "location": "Lugar",
        "participant": "Participantes.",
        "get_data_exception": "Excepción al traer los datos.",
        "new_event": "Evento Nuevo",
        "confirm_delete_event": "Estas seguro de eliminar este evento?",
        "confrim_delete_event_or_all": "Quieres eliminar todos los eventos o solo este? \r\nPresiona [OK] para eliminar este evento, Presiona [Cancel] para eliminarlos todos.",
        "data_format_error": "Error en el formato de los datos.",
        "invalid_title": "EL titulo no puede ir en blanco o contener ($<>)",
        "view_no_ready": "La vista no esta lista",
        "example": "Ejemplo A6206",
        "content": "Evento",
        "create_event": "Crear nuevo evento.",
        "update_detail": "Editar detalles.",
        "click_to_detail": "Ver detalles.",
        "i_delete": "Eliminar",
        "day_plural": "dias",
        "others": "Otros",
        "item": ""
    }
});
